apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}
spec:
  replicas: {{.Values.app_replicas}}
  selector:
    matchLabels:
      app: {{.Values.app_name}}
  template:
    metadata:
      labels:
        app: {{.Values.app_name}}
    spec:
      containers:
      - name: {{.Values.app_name}}
        image: {{.Values.image_url}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.container_port}}