apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}-svc
spec:
  selector:
    app: {{.Values.app_name}}
  ports:
  - port: 80
    name: {{.Values.app_name}}
    targetPort: {{.Values.container_port}}
  type: ClusterIP