apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}-svc
spec:
  selector:
    app: {{.Values.app_name}}
  ports:
  - port: {{.Values.service_port}}
    targetPort: {{.Values.container_port}}